### ISSUE TITLE
numerical result

### ISSUE THREAD

**Issue by arily** [brussell98/node-osu#10]
the value of id, counts, scores, pp .. are strings.

it would be better if int values returns as int, float as float.

I collected a lot of scores without noticing that pp result are strings until I tried to query my database (like "bp.pp > 500" and get result like '9.04567').

**Comment by brussell98** [comment]
Hmm, I'll see what I can do about this. The main issue is this will allow for integer overflow, and BigInt hasn't been out long enough to use that.

**Comment by arily** [comment]
Hi,
Thanks for the fast response.
Maybe we can convert string to int, then convert it back to string and compare it to the original string?
As long as they are matching, it should be fine.
And return strings when it eventually overflowed.

**Comment by brussell98** [comment]
Added in v2.1.0
