### ISSUE TITLE
getMatch throws Error

### ISSUE THREAD

**Issue by arily** [brussell98/node-osu#11]
(node:41350) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'match' of undefined
    at /node_modules/node-osu/lib/Api.js:108:21
it seems the response of /get_match is not an array.

**Comment by arily** [comment]
{
  match: {
    match_id: '57436825',
    name: 'EWC s0 1400-1800: (arily) vs (hlvck255)',
    start_time: '2020-01-02 13:26:18',
    end_time: '2020-01-02 14:26:14'
  },
 games: [...]
}
this is the result when I use apiCall()

**Comment by brussell98** [comment]
Fixed in 105dc1a
