### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by GDcheerios** [brussell98/node-osu#19]
I don't know crap about js but I am trying to use this for a osu website, I am getting this error I will send a screenshot and maybe you can explain what is happening 
![image](https://user-images.githubusercontent.com/54640414/104765392-718b5180-572e-11eb-8252-ee61d292fc43.png)

**Comment by Edqe14** [comment]
You need to add a `catch` on the promise and I believe it won't log `Promise` on the console, maybe you want to restart the script and try again.

Also, you might want to regenerate a new API token because you leaked it on the screenshot.

**Comment by GDcheerios** [comment]
oh thew api was what was in the code already

**Comment by brussell98** [comment]
GitHub issues are not a place to learn how to program.
