### ISSUE TITLE
pp returns null

### ISSUE THREAD

**Issue by jannes-io** [brussell98/node-osu#2]
As seen in the attachment.
![image](https://user-images.githubusercontent.com/9079379/30514301-4ffd3ee2-9b12-11e7-8ebd-b9768834d4ba.png)

Map I played was ranked.

PS: username is also empty but since this is input for the getRecentScore we already have it so it seems obsolete.

**Comment by brussell98** [comment]
That's because the osu api does not return pp for recent score. IDK why but that's what it shows [here](https://github.com/ppy/osu-api/wiki#response-4)

**Comment by jannes-io** [comment]
Alright. I'll get in contact with Peppy and see if I can get some information on that.

**Comment by jannes-io** [comment]
Reply from Peppy:
"recent scores don’t have pp values calculated. they are a completely different beast (they include non-passing scores etc.)"

Which gets me on the the next question:
If I make an instance of the api with completed scores on, does that show pp? (not home now so can't test)

**Comment by brussell98** [comment]
No, the `completeScores` option just makes sure that scores return with full beatmap data
