### ISSUE TITLE
getUserBest only gets top 10 scores, not top 100.

### ISSUE THREAD

**Issue by Duckbio** [brussell98/node-osu#20]
I'm not sure if this is intended or not, but getUserBest is only making an array of top 10 user scores. If there's a _fix_ for this please help me!

**Comment by brussell98** [comment]
Please provide the code you are using. Setting `limit` should allow up to 500 results.

**Comment by Duckbio** [comment]
`
    client.osu.getUserBest({ u: user.name}).then(async scores => {
        //code here...
    }
`
This is pretty much it, user.name works properly but if I try to use something like scores[20] for example it just returns an error saying it cannot read the property of scores, so scores is empty from scores[12] on from what I have tested.

**Comment by brussell98** [comment]
Not an issue, [working as intended](https://github.com/ppy/osu-api/wiki#parameters-3).
Use the limit option.
