### ISSUE TITLE
index.d.ts needs moving into a tagged version

### ISSUE THREAD

**Issue by NattieGit** [brussell98/node-osu#22]
Currently, the `index.d.ts` file for Typescript only exists on the master branch and not in any tagged version.

As a result, when installing this package through npm, the package can't (easily) be used with Typescript. I've currently worked around it by referencing the git repo and master branch in my package.json file, however it would be much nicer to just have typescript supported in an npm version.

Hopefully you can get around to doing it :)

Love this package so far. Well done on making it.

**Comment by brussell98** [comment]
Released version 2.2.1 with types
