### ISSUE TITLE
NightCore returns star rating to 0

### ISSUE THREAD

**Issue by AuracleTech** [brussell98/node-osu#23]
NightCore is supposed to do the same as DT, yet returns star rating to 0.

```
osuApi.getBeatmaps({ b: '765567', mods: [512] }).then(beatmaps => {
    console.log("beatmap", beatmaps[0]);
});
```
Result

![image](https://user-images.githubusercontent.com/40531871/112425946-61cf5100-8d0d-11eb-8b16-66a30d4631ce.png)

[512](https://github.com/ppy/osu-api/wiki#mods) is supposed to be NightCore
For now I have to use 64 for NC (Which is DT)

**Comment by brussell98** [comment]
This has nothing to do with this library.

As the osu api docs you linked say, you can only set NC if DT is also set.
