### ISSUE TITLE
Beatmap stuff

### ISSUE THREAD

**Issue by Kade-github** [brussell98/node-osu#4]
So im making a discord bot right, and i want the getUserBest part of the bot to show the beatmap title as well here is my code:
https://hastebin.com/zipafiyiqo.js

Edit:
I just want to know how i can implent that into my code. I've tried and failed.

**Comment by brussell98** [comment]
There is a client option for that. See the `completeScores` option in https://github.com/brussell98/node-osu/blob/master/README.md#constructor
This makes the response of score endpoints return an array of [score, beatmap], as seen in https://github.com/brussell98/node-osu/blob/master/README.md#getuserbestoptions

**Comment by Kade-github** [comment]
ahhh thanks so much
