### ISSUE TITLE
Beatmap undefined

### ISSUE THREAD

**Issue by ZeroSiks** [brussell98/node-osu#5]
`osuApi.getScores` with `completeScores` set to true does not return the beatmap array? Score array shows up just fine.

Other score endpoints are working as intended it's just the getScores one

**Comment by ZeroSiks** [comment]
Also username is missing in the score array

**Comment by brussell98** [comment]
I'm unable to reproduce this without detailed information, and this issue has been inactive for months so I will be closing it.
